services:
  rabbitmq-broker:
    image: rabbitmq:3-management-alpine
    container_name: receipt-rabbitmq-broker
    ports:
      - "5672:5672"   
      - "15672:15672" 
    restart: always

  minio-storage:
    image: minio/minio
    container_name: receipt-object-storage
    ports:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    restart: always